import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../service/task_provider.dart';
import '../model/task.dart';

class CreateTaskPage extends ConsumerStatefulWidget {
  const CreateTaskPage({super.key});

  @override
  ConsumerState<CreateTaskPage> createState() => _CreateTaskPageState();
}

class _CreateTaskPageState extends ConsumerState<CreateTaskPage> {
  final _formKey = GlobalKey<FormState>();

  final TextEditingController titleCtrl = TextEditingController();
  final TextEditingController descCtrl = TextEditingController();
  final TextEditingController assignedCtrl = TextEditingController();

  final TextEditingController dueDateCtrl = TextEditingController();
  DateTime? _selectedDueDate;

  String? _selectedCategory;
  String? _selectedPriority;

  final List<String> _categories = [
    'scheduling',
    'finance',
    'technical',
    'safety',
    'general',
  ];
  final List<String> _priorities = ['high', 'medium', 'low'];

  bool loading = false;
  bool showPreview = false;
  Map<String, dynamic>? classificationPreview;

  void _generatePreview() {
    if (titleCtrl.text.isEmpty || descCtrl.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please fill title and description')),
      );
      return;
    }

    // Simple client-side classification for preview
    final fullText = '${titleCtrl.text} ${descCtrl.text}'.toLowerCase();

    String category = 'general';
    if (fullText.contains(
      RegExp(r'\b(meeting|schedule|call|appointment|deadline)\b'),
    )) {
      category = 'scheduling';
    } else if (fullText.contains(
      RegExp(r'\b(payment|invoice|bill|budget|cost|expense)\b'),
    )) {
      category = 'finance';
    } else if (fullText.contains(
      RegExp(r'\b(bug|fix|error|install|repair|maintain)\b'),
    )) {
      category = 'technical';
    } else if (fullText.contains(
      RegExp(r'\b(safety|hazard|inspection|compliance|ppe)\b'),
    )) {
      category = 'safety';
    }

    String priority = 'medium';
    if (fullText.contains(
      RegExp(r'\b(urgent|asap|immediately|today|critical|emergency)\b'),
    )) {
      priority = 'high';
    } else if (fullText.contains(RegExp(r'\b(soon|this week|important)\b'))) {
      priority = 'medium';
    } else {
      priority = 'low';
    }

    setState(() {
      _selectedCategory = category;
      _selectedPriority = priority;
      classificationPreview = {
        'category': category,
        'priority': priority,
        'message':
            'Auto-classification preview generated based on content analysis',
      };
      showPreview = true;
    });
  }

  Future<void> submitTask() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => loading = true);

    final task = Task(
      id: '', // ID is generated by the backend
      title: titleCtrl.text,
      description: descCtrl.text,
      category: _selectedCategory!,
      priority: _selectedPriority!,
      status: 'pending',
      assignedTo: assignedCtrl.text.isEmpty ? 'Unassigned' : assignedCtrl.text,
      dueDate: _selectedDueDate ?? DateTime.now().add(const Duration(days: 1)),
      extractedEntities: [],
      suggestedActions: [],
    );

    try {
      await ref.read(taskServiceProvider).createTask(task);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Task created successfully')),
        );
        Navigator.pop(context, true); // Return true to indicate success
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Failed to create task: $e')));
      }
    } finally {
      if (mounted) {
        setState(() => loading = false);
      }
    }
  }

  @override
  void dispose() {
    titleCtrl.dispose();
    descCtrl.dispose();
    assignedCtrl.dispose();

    dueDateCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom,
      ),
      child: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text(
                      'Create New Task',
                      style: TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.close),
                      onPressed: () => Navigator.pop(context),
                    ),
                  ],
                ),
                const Divider(),
                const SizedBox(height: 16),
                TextFormField(
                  controller: titleCtrl,
                  decoration: InputDecoration(
                    labelText: 'Title *',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                    prefixIcon: const Icon(Icons.title),
                  ),
                  validator: (v) =>
                      v == null || v.isEmpty ? 'Title required' : null,
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: descCtrl,
                  maxLines: 4,
                  decoration: InputDecoration(
                    labelText: 'Description *',
                    hintText: 'Used for auto-classification',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                    prefixIcon: const Icon(Icons.description),
                  ),
                  validator: (v) =>
                      v == null || v.isEmpty ? 'Description required' : null,
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: assignedCtrl,
                  decoration: InputDecoration(
                    labelText: 'Assigned To',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                    prefixIcon: const Icon(Icons.person),
                  ),
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: dueDateCtrl,
                  readOnly: true,
                  decoration: InputDecoration(
                    labelText: 'Due Date',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                    prefixIcon: const Icon(Icons.calendar_today),
                  ),
                  onTap: () async {
                    final date = await showDatePicker(
                      context: context,
                      initialDate: _selectedDueDate ?? DateTime.now(),
                      firstDate: DateTime.now(),
                      lastDate: DateTime.now().add(const Duration(days: 365)),
                    );
                    if (date != null) {
                      setState(() {
                        _selectedDueDate = date;
                        dueDateCtrl.text = date.toString().split(' ')[0];
                      });
                    }
                  },
                ),
                const SizedBox(height: 16),
                _buildAutoClassificationSection(),
                const SizedBox(height: 16),
                DropdownButtonFormField<String>(
                  initialValue: _selectedCategory,
                  onChanged: (value) =>
                      setState(() => _selectedCategory = value),
                  items: _categories
                      .map((c) => DropdownMenuItem(value: c, child: Text(c)))
                      .toList(),
                  decoration: InputDecoration(
                    labelText: 'Category *',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                    prefixIcon: const Icon(Icons.category),
                  ),
                  validator: (v) => v == null ? 'Category required' : null,
                ),
                const SizedBox(height: 12),
                DropdownButtonFormField<String>(
                  initialValue: _selectedPriority,
                  onChanged: (value) =>
                      setState(() => _selectedPriority = value),
                  items: _priorities
                      .map((p) => DropdownMenuItem(value: p, child: Text(p)))
                      .toList(),
                  decoration: InputDecoration(
                    labelText: 'Priority *',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                    prefixIcon: const Icon(Icons.flag),
                  ),
                  validator: (v) => v == null ? 'Priority required' : null,
                ),
                const SizedBox(height: 12),
                TextFormField(
                  initialValue: 'pending',
                  enabled: false,
                  decoration: InputDecoration(
                    labelText: 'Status',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                    prefixIcon: const Icon(Icons.info),
                  ),
                ),
                const SizedBox(height: 24),
                SizedBox(
                  width: double.infinity,
                  height: 48,
                  child: ElevatedButton.icon(
                    onPressed: loading ? null : submitTask,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.deepPurple,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                    icon: loading
                        ? const SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              color: Colors.white,
                            ),
                          )
                        : const Icon(Icons.save),
                    label: Text(loading ? 'Creating...' : 'Create Task'),
                  ),
                ),
                const SizedBox(height: 16),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildAutoClassificationSection() {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Colors.blue.shade50,
        border: Border.all(color: Colors.blue.shade200),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Row(
            children: [
              Icon(Icons.auto_awesome, color: Colors.blue),
              SizedBox(width: 8),
              Text(
                'Auto-Classification Preview',
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
              ),
            ],
          ),
          const SizedBox(height: 8),
          if (showPreview && classificationPreview != null) ...[
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: Colors.green.shade50,
                border: Border.all(color: Colors.green),
                borderRadius: BorderRadius.circular(4),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      const Icon(
                        Icons.check_circle,
                        color: Colors.green,
                        size: 16,
                      ),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Text(
                          classificationPreview!['message'] ?? '',
                          style: const TextStyle(fontSize: 12),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 8),
                  Wrap(
                    spacing: 8,
                    children: [
                      Chip(
                        label: Text(
                          'Category: ${classificationPreview!['category']}',
                          style: const TextStyle(fontSize: 12),
                        ),
                        backgroundColor: Colors.green.shade100,
                      ),
                      Chip(
                        label: Text(
                          'Priority: ${classificationPreview!['priority']}',
                          style: const TextStyle(fontSize: 12),
                        ),
                        backgroundColor: Colors.orange.shade100,
                      ),
                    ],
                  ),
                  const SizedBox(height: 8),
                  const Text(
                    'You can override these values below if needed.',
                    style: TextStyle(fontSize: 11, fontStyle: FontStyle.italic),
                  ),
                ],
              ),
            ),
          ] else ...[
            Text(
              'Click "Generate Classification" to auto-fill category & priority.',
              style: TextStyle(fontSize: 12, color: Colors.blue.shade700),
            ),
          ],
          const SizedBox(height: 8),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              onPressed: _generatePreview,
              icon: const Icon(Icons.smart_toy),
              label: const Text('Generate Classification'),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.blue.shade700,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
